const int headerSize= 44;
byte header[44];

void wavHeader(byte* header, int wavSize){
  BITS_PER_SAMPLE = RESOLUTION;
  BYTE_RATE  = (RESOLUTION * CHANNELS *SAMPLE_RATE)/8;
  BYTES_PER_FRAME = (BITS_PER_SAMPLE * CHANNELS)/8;
  header[0] = 'R';
  header[1] = 'I';
  header[2] = 'F';
  header[3] = 'F';
  unsigned int fileSize = wavSize + headerSize - 8;
  header[4] = (byte)(fileSize & 0xFF);
  header[5] = (byte)((fileSize >> 8) & 0xFF);
  header[6] = (byte)((fileSize >> 16) & 0xFF);
  header[7] = (byte)((fileSize >> 24) & 0xFF);
  header[8] = 'W';
  header[9] = 'A';
  header[10] = 'V';
  header[11] = 'E';
  header[12] = 'f';
  header[13] = 'm';
  header[14] = 't';
  header[15] = ' ';
  header[16] = (byte)(RESOLUTION & 0xFF);//0x10;                      //LENGTH OF FORMAT DATA
  header[17] = (byte)((RESOLUTION >> 8) & 0xFF);//0x00;
  header[18] = (byte)((RESOLUTION >> 16) & 0xFF);//0x00;
  header[19] = (byte)((RESOLUTION >> 24) & 0xFF);//0x00;
  header[20] = 0x01;
  header[21] = 0x00;
  header[22] = (byte)(CHANNELS & 0xFF);//0x01;                        //CHANNELS
  header[23] = (byte)((CHANNELS >> 8) & 0xFF);//0x00;
  header[24] = (byte)(SAMPLE_RATE & 0xFF);//0x44;//0x80;              //SAMPLE RATE
  header[25] = (byte)((SAMPLE_RATE >> 8) & 0xFF);//0xAC;//0x3E;
  header[26] = (byte)((SAMPLE_RATE >> 16) & 0xFF);//0x00;
  header[27] = (byte)((SAMPLE_RATE >> 24) & 0xFF);//0x00;
  header[28] = (byte)(BYTE_RATE & 0xFF);//0x88;//0x00;                //BYTE_RATE
  header[29] = (byte)((BYTE_RATE >> 8) & 0xFF);//0x58;//0x7D;
  header[30] = (byte)((BYTE_RATE >> 16) & 0xFF);//0x01;//0x00;
  header[31] = (byte)((BYTE_RATE >> 24) & 0xFF);//0x00;
  header[32] = (byte)(BYTES_PER_FRAME & 0xFF);//0x02;                 //BYTE_PER_FRAME
  header[33] = (byte)((BYTES_PER_FRAME >> 8) & 0xFF);//0x00;
  header[34] = (byte)(RESOLUTION & 0xFF);//0x10;                      //BITS_PER_SAMPLE
  header[35] = (byte)((RESOLUTION >> 8) & 0xFF);//0x00;
  header[36] = 'd';
  header[37] = 'a';
  header[38] = 't';
  header[39] = 'a';
  header[40] = (byte)(wavSize & 0xFF);
  header[41] = (byte)((wavSize >> 8) & 0xFF);
  header[42] = (byte)((wavSize >> 16) & 0xFF);
  header[43] = (byte)((wavSize >> 24) & 0xFF);
}
